# Generated by Django 4.2.7 on 2023-12-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterforge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
