# Generated by Django 4.2.7 on 2023-12-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterforge', '0003_alter_characterspell_level_learned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
